### ISSUE TITLE
Coveralls that can be improved(read the comments)

### ISSUE THREAD

**Issue by jing1324** [CS2103-AY1819S2-W09-2/main#100]
This list can be updated as necessary and it contains all Classes that has less than 80% coveralls.
Everything in Requests Folder + VersionedRequestsBook + RequestBook
ModelManager
VersionedPatient book and PatientBook (To be deleted)?
SampleData.util
StorageManager
HealthWorkerCard
HealthWorkerListPanel
UiManager
MainApp

**Comment by huichun66** [comment]
Will work on the UI related components test coverage in this milestone.

**Comment by jing1324** [comment]
refer to Issue #130 for updated list
