### ISSUE TITLE
List of tests to be rewritten after removal of Addressbook

### ISSUE THREAD

**Issue by jing1324** [CS2103-AY1819S2-W09-2/main#130]
All System Tests:
AddPersonCommandSystemTest
~~AddressBookSystemTest~~ (Changed to HealthHubSystemTest)
ClearCommandSystemTest
~~DeletePersonCommandSystemTest~~ (Changed to DeleteRequestCommandSystemTest)
EditPersonCommandSystemTest
~~FindCommandSystemTest~~ (Changed to FilterRequestCommandSystemTest)
~~HelpCommandSystemTest~~
~~ModelHelper.java~~
~~SampleDataTest.java~~
~~SelectCommandSystemTest~~

Model Tests:
ModelManagerTest
AddressBookParserTest
LogicManagerTest
CommandTestUtil
~~TestApp.java~~
EditHealthWorkerCommandTest

**Comment by jing1324** [comment]
Guys we have a lot of tests to rewrite, please take your share and do when you are free and cross out when completed

**Comment by huichun66** [comment]
Let me work on the SystemTests, I'm complete with the UI work.

**Comment by jing1324** [comment]
Most of the tests have been completed
