### ISSUE TITLE
Assign command bug 

### ISSUE THREAD

**Issue by daviddl9** [CS2103-AY1819S2-W09-2/main#131]
Assign command bug that does not change status of request after healthworker has been assigned

**Comment by jing1324** [comment]
Assign command now changes a completed request to ongoing after healthworker has assigned

**Comment by huichun66** [comment]
There is a bug, you can assign an already 'ongoin' request to 'ongoing' status, the command message is still the same.

**Comment by daviddl9** [comment]
refer to pr #142
