### ISSUE TITLE
Minor UI bug for command box, key press not that responsive.

### ISSUE THREAD

**Issue by huichun66** [CS2103-AY1819S2-W09-2/main#138]
Does not affect main functionality but upon closer inspection, sometimes you have to perform multiple keycodes before registering the intended input. 

i.e. to select a suggestion from autocomplete, the app currently does require you to type in some words then type backspace till the end, type the prefixes again and you will be able to select from the dropdown.

**Comment by huichun66** [comment]
![image](https://user-images.githubusercontent.com/7857839/55295000-ffebf180-543a-11e9-85da-30d5611813cf.png)

* Not an error, but a warning I've been wanting to fix since the beginning of time. :worried:

**Comment by jing1324** [comment]
We have decided not to fix it.
