### ISSUE TITLE
Small add request bug

### ISSUE THREAD

**Issue by dreampursuer95** [CS2103-AY1819S2-W09-2/main#163]
Not really a bug, but when add request is in the wrong format, the example does not show NRIC

Invalid command format! 

add: Creates a new request in the request book.
Parameters: n/NAME i/NRIC p/PHONE a/ADDRESS dt/DATETIME c/CONDITION...
Example: add request n/John Doe p/81234567 a/123, Sengkang Ave 3, #04-12, 214632 dt/01-01-2019 08:00:00 c/Physiotherapy
^ missing i/NRIC in the example

**Comment by dreampursuer95** [comment]
also, the add command format in user guide and the actual application are a little different in order of the parameters. Maybe need to revise that to avoid confusion.

**Comment by dreampursuer95** [comment]
also, I seem to be able to add two identical requests, each differing only by a condition
Example:
add request n/Yoon Ki Hyun i/S8444421C p/98765433 a/123 Brick Road, #01-01 dt/01-01-2019 14:50:00 c/Diabetic c/Physiotherapy c/dead c/alive
add request n/Yoon Ki Hyun i/S8444421C p/98765433 a/123 Brick Road, #01-01 dt/01-01-2019 14:50:00 c/Diabetic c/Physiotherapy c/dead 
^ both are added
Just wondering if it is intended.

**Comment by dreampursuer95** [comment]
There is no limit to the year input in add request
Example: add request n/John Pan i/S0898543H p/90897867 a/NUS dt/03-04-20199 02:05:33 c/fomo
putting 20199 as year by accident works

**Comment by jing1324** [comment]
Issue has been fixed as of PR #210
