### ISSUE TITLE
Delete request bug

### ISSUE THREAD

**Issue by dreampursuer95** [CS2103-AY1819S2-W09-2/main#165]
After deleting a request, deleting another request does not work.

**Comment by dreampursuer95** [comment]
Invalid command format! 

The different modes for editing an existing item are as follows:

delete: Deletes the health worker identified by the index number used in the displayed health worker list.
Parameters: INDEX (must be a positive integer)
Example: delete 1

^ the example should be edited to delete request 1

**Comment by daviddl9** [comment]
Documentation issue fixed in #207
