### ISSUE TITLE
Bug in getPatientBook() triggering NullPointerException

### ISSUE THREAD

**Issue by daviddl9** [CS2103-AY1819S2-W09-2/main#78]
`getPatientBook()` has a bug that triggers a `NullPointerException` when the system tests run.

**Comment by jing1324** [comment]
The tests still fail even after the bug gets resolved

**Comment by daviddl9** [comment]
The issue is with the storage of the `PatientBook`. The `ModelManager` has an incorrect implementation of the `PatientBook` storage

**Comment by jing1324** [comment]
Issue has been resolved
